config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'home' => 'dashboard#home'

  get 'history' => 'dashboard#history'

  get 'settings' => 'dashboard#settings'

  root to: 'visitors#index'
  get 'signup' => 'users#new'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/auth/failure' => 'sessions#failure'

  resources :textbook_matches
  resources :textbooks
  resources :textbook_requests
  resources :textbook_offers
  resources :users
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/textbook_request.rb
class TextbookRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :textbook
end

app/controllers/textbook_requests_controller.rb
class TextbookRequestsController < ApplicationController
  before_action :set_textbook_request, only: [:show, :edit, :update, :destroy]

  # GET /textbook_requests
  # GET /textbook_requests.json
  def index
    @textbook_requests = TextbookRequest.all
  end

  # GET /textbook_requests/1
  # GET /textbook_requests/1.json
  def show
  end

  # GET /textbook_requests/new
  def new
    @textbook_request = TextbookRequest.new
  end

  # GET /textbook_requests/1/edit
  def edit
  end

  # POST /textbook_requests
  # POST /textbook_requests.json
  def create
    @textbook_request = TextbookRequest.new(textbook_request_params)

    respond_to do |format|
      if @textbook_request.save
        format.html { redirect_to @textbook_request, notice: 'Textbook request was successfully created.' }
        format.json { render :show, status: :created, location: @textbook_request }
      else
        format.html { render :new }
        format.json { render json: @textbook_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /textbook_requests/1
  # PATCH/PUT /textbook_requests/1.json
  def update
    respond_to do |format|
      if @textbook_request.update(textbook_request_params)
        format.html { redirect_to @textbook_request, notice: 'Textbook request was successfully updated.' }
        format.json { render :show, status: :ok, location: @textbook_request }
      else
        format.html { render :edit }
        format.json { render json: @textbook_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /textbook_requests/1
  # DELETE /textbook_requests/1.json
  def destroy
    @textbook_request.destroy
    respond_to do |format|
      format.html { redirect_to textbook_requests_url, notice: 'Textbook request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_textbook_request
      @textbook_request = TextbookRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def textbook_request_params
      params.require(:textbook_request).permit(:user_id, :textbook_id)
    end
end

app/helpers/textbook_requests_helper.rb
module TextbookRequestsHelper
end

app/views/textbook_requests/_form.html.erb
<%= simple_form_for(@textbook_request) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :textbook_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/textbook_requests/edit.html.erb
<h1>Editing Textbook Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @textbook_request %> |
<%= link_to 'Back', textbook_requests_path %>

app/views/textbook_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Textbook Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Textbook</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @textbook_requests.each do |textbook_request| %>
      <tr>
        <td><%= textbook_request.user_id %></td>
        <td><%= textbook_request.textbook_id %></td>
        <td><%= link_to 'Show', textbook_request %></td>
        <td><%= link_to 'Edit', edit_textbook_request_path(textbook_request) %></td>
        <td><%= link_to 'Destroy', textbook_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Textbook request', new_textbook_request_path %>

app/views/textbook_requests/new.html.erb
<h1>New Textbook Request</h1>

<%= render 'form' %>

<%= link_to 'Back', textbook_requests_path %>

app/views/textbook_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @textbook_request.user_id %>
</p>

<p>
  <strong>Textbook:</strong>
  <%= @textbook_request.textbook_id %>
</p>

<%= link_to 'Edit', edit_textbook_request_path(@textbook_request) %> |
<%= link_to 'Back', textbook_requests_path %>