config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'home' => 'dashboard#home'

  get 'history' => 'dashboard#history'

  get 'settings' => 'dashboard#settings'

  root to: 'visitors#index'
  get 'signup' => 'users#new'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/auth/failure' => 'sessions#failure'

  resources :textbook_matches
  resources :textbooks
  resources :textbook_requests
  resources :textbook_offers
  resources :users
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/textbook.rb
class Textbook < ActiveRecord::Base
end

app/controllers/textbooks_controller.rb
class TextbooksController < ApplicationController
  before_action :set_textbook, only: [:show, :edit, :update, :destroy]

  # GET /textbooks
  # GET /textbooks.json
  def index
    @textbooks = Textbook.all
  end

  # GET /textbooks/1
  # GET /textbooks/1.json
  def show
  end

  # GET /textbooks/new
  def new
    @textbook = Textbook.new
  end

  # GET /textbooks/1/edit
  def edit
  end

  # POST /textbooks
  # POST /textbooks.json
  def create
    @textbook = Textbook.new(textbook_params)

    respond_to do |format|
      if @textbook.save
        format.html { redirect_to @textbook, notice: 'Textbook was successfully created.' }
        format.json { render :show, status: :created, location: @textbook }
      else
        format.html { render :new }
        format.json { render json: @textbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /textbooks/1
  # PATCH/PUT /textbooks/1.json
  def update
    respond_to do |format|
      if @textbook.update(textbook_params)
        format.html { redirect_to @textbook, notice: 'Textbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @textbook }
      else
        format.html { render :edit }
        format.json { render json: @textbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /textbooks/1
  # DELETE /textbooks/1.json
  def destroy
    @textbook.destroy
    respond_to do |format|
      format.html { redirect_to textbooks_url, notice: 'Textbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_textbook
      @textbook = Textbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def textbook_params
      params.require(:textbook).permit(:title, :isbn)
    end
end

app/helpers/textbooks_helper.rb
module TextbooksHelper
end

app/views/textbooks/_form.html.erb
<%= simple_form_for(@textbook) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :isbn %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/textbooks/edit.html.erb
<h1>Editing Textbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @textbook %> |
<%= link_to 'Back', textbooks_path %>

app/views/textbooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Textbooks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @textbooks.each do |textbook| %>
      <tr>
        <td><%= textbook.title %></td>
        <td><%= textbook.isbn %></td>
        <td><%= link_to 'Show', textbook %></td>
        <td><%= link_to 'Edit', edit_textbook_path(textbook) %></td>
        <td><%= link_to 'Destroy', textbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Textbook', new_textbook_path %>

app/views/textbooks/new.html.erb
<h1>New Textbook</h1>

<%= render 'form' %>

<%= link_to 'Back', textbooks_path %>

app/views/textbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @textbook.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @textbook.isbn %>
</p>

<%= link_to 'Edit', edit_textbook_path(@textbook) %> |
<%= link_to 'Back', textbooks_path %>